insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (1, 'Manslaughter', 'Dewain Long', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 1, 'Drama', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (2, 'Hound of the Baskervilles, The', 'Lorene Hrihorovich', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 3, 'Comedy|Crime|Mystery', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (3, 'House of Wax', 'Rosemarie Yanez', 'Nunc purus.', 3, 'Crime|Horror|Mystery|Thriller', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (4, 'Benigni', 'Kelcey Hexum', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1, 'Animation|Comedy|Drama', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (5, 'One Night of Love', 'Ulrick Oolahan', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 10, 'Romance', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (6, 'Stendhal Syndrome, The (Sindrome di Stendhal, La)', 'Afton Klemt', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 5, 'Crime|Horror|Thriller', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (7, 'Skipped Parts', 'Min Touson', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, 'Drama|Romance', 'http://dummyimage.com/200x250.png/ff4444/ffffff');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (8, 'Love Songs (Les chansons d''amour)', 'Cassondra Arsey', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 7, 'Drama|Musical', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (9, 'Hollow Triumph (a.k.a. The Scar)', 'Opal Meagher', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 3, 'Crime|Drama|Film-Noir', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (10, 'Once Upon a Forest', 'Cate Hodcroft', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 6, 'Adventure|Animation|Children|Fantasy', 'https://picsum.photos/200/250');
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (11, 'Palabras Ordenadas', 'David Jiménez Villarejo', 'En este libro están recopilados todos los relatos y poemas que he ido escribiendo. En ellos, plasmo lo que he sentido y siento; espero que disfrutéis leyéndolos y que os haga pensar en algo especial de vosotros.', 10, 'Poesía|Amor|Relatos', 'https://i.imgur.com/X4hJkcZ.jpg'),
insert into Libros (idLibro, tituloLibro, autorLibro, descripcionLibro, puntuacionLibro, generoLibro, imagenLibro) values (12, 'El Hogar', 'David Jiménez Villarejo', '1985, en las afueras de Bridge Rock, una cabaña espera nuevos inquilinos. En un lugar maravilloso, rodeada de un bosque y con un gran lago de agua cristalina a su lado, pero sin personas que hayan vivido en ella en más de veinte años, ¿o igual sí?\n\nConoce la historia de Érica Wilson en este relato corto, una niña de diez años que llega con sus padres a un nuevo hogar. Sumérgete hasta el final para saber qué misterio le espera en su vida. ¿Será capaz de encontrar una respuesta para lo que ocurre?', 10, 'Horror|Misterio|Terror', 'https://i.imgur.com/DInFju2.jpg');

