-- MySQL Script generated by MySQL Workbench
-- mar 16 feb 2021 10:57:43 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `emailUsuario` VARCHAR(150) NULL,
  `passwordUsuario` VARCHAR(20) NULL,
  `rolUsuario` VARCHAR(45) NULL,
  `multaUsuario` INT NULL,
  `multaHasta` DATE NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Libros` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `tituloLibro` VARCHAR(70) NULL,
  `autorLibro` VARCHAR(150) NULL,
  `descripcionLibro` MEDIUMTEXT NULL,
  `puntuacionLibro` INT NULL,
  `generoLibro` VARCHAR(45) NULL,
  `imagenLibro` VARCHAR(300) NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Libros_prestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Libros_prestados` (
  `idUsuario` INT NOT NULL,
  `idLibro` INT NOT NULL,
  `fechaDevolver` DATE NULL,
  INDEX `fk_Libros_prestados_Libros_idx` (`idLibro` ASC),
  CONSTRAINT `fk_Libros_prestados_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `biblioteca`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_prestados_Libros`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Comentarios` (
  `idUsuario` INT NOT NULL,
  `idLibro` INT NOT NULL,
  `comentario` VARCHAR(250) NULL,
  INDEX `fk_Usuarios_has_Libros_Libros2_idx` (`idLibro` ASC),
  INDEX `fk_Usuarios_has_Libros_Usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuarios_has_Libros_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `biblioteca`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Libros_Libros2`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca`.`Libros` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
